/*
 * Generated on: 2023-10-27 20:26:55
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#ifndef WPP_LWM2M_SECURITY_CONFIG_H
#define WPP_LWM2M_SECURITY_CONFIG_H

#if OBJ_M_0_LWM2M_SECURITY_V11

/* --------------- Config block 0 start --------------- */
#define RES_0_10 1
#define RES_0_11 1
#define RES_0_12 1
/* --------------- Config block 0 end --------------- */

#endif // WPP_LWM2M_SECURITY_CONFIG_H
#endif // OBJ_M_0_LWM2M_SECURITY_V11
