#ifndef WPP_LWM2M_SECURITY_CONFIG_H
#define WPP_LWM2M_SECURITY_CONFIG_H

#if OBJ_M_0_LWM2M_SECURITY_V12

/* ---------- Server optional resources start ---------- */

#define RES_0_6_SMS_SECURITY_MODE 0
#define RES_0_7_SMS_BINDING_KEY_PARAMETERS 0
#define RES_0_8_SMS_BINDING_SECRET_KEY_S_ 0
#define RES_0_9_LWM2M_SERVER_SMS_NUMBER 0
#define RES_0_10_SHORT_SERVER_ID 1
#define RES_0_11_CLIENT_HOLD_OFF_TIME 1
#define RES_0_12_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT 1
#define RES_0_13_MATCHING_TYPE 0
#define RES_0_14_SNI 0
#define RES_0_15_CERTIFICATE_USAGE 0
#define RES_0_16_DTLS_TLS_CIPHERSUITE 0
#define RES_0_17_OSCORE_SECURITY_MODE 0
#define RES_0_18_GROUPS_TO_USE_BY_CLIENT 0
#define RES_0_19_SIGNATURE_ALGORITHMS_SUPPORTED_BY_SERVER 0
#define RES_0_20_SIGNATURE_ALGORITHMS_TO_USE_BY_CLIENT 0
#define RES_0_21_SIGNATURE_ALGORITHM_CERTS_SUPPORTED_BY_SERVER 0
#define RES_0_22_TLS_1_3_FEATURES_TO_USE_BY_CLIENT 0
#define RES_0_23_TLS_EXTENSIONS_SUPPORTED_BY_SERVER 0
#define RES_0_24_TLS_EXTENSIONS_TO_USE_BY_CLIENT 0
#define RES_0_25_SECONDARY_LWM2M_SERVER_URI 0
#define RES_0_26_MQTT_SERVER 0
#define RES_0_27_LWM2M_COSE_SECURITY 0
#define RES_0_28_RDS_DESTINATION_PORT 0
#define RES_0_29_RDS_SOURCE_PORT 0
#define RES_0_30_RDS_APPLICATION_ID 0

/* ---------- Server optional resources end ---------- */

/* --------------- Config block 0 start --------------- */
/* --------------- Config block 0 end --------------- */

#endif // WPP_LWM2M_SECURITY_CONFIG_H
#endif // OBJ_M_0_LWM2M_SECURITY_V12
