/*
 * Device
 * Generated on: 2023-10-12 16:31:46.234714
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#include "m_3_device_v12/Device.h"

#include <unordered_map>
#include <iostream>

#include "Resource.h"
#include "ResOp.h"
#include "types.h"
#include "WppLogs.h"

/* --------------- Code_cpp block 0 start --------------- */
#if RES_3_9_BATTERY_LEVEL
#define BUTT_LVL_MIN	0
#define BUTT_LVL_MAX	100
#endif
/* --------------- Code_cpp block 0 end --------------- */

#define TAG "Device"

namespace wpp {

Device::Device(lwm2m_context_t &context, const OBJ_LINK_T &id): Instance(context, id) {

	/* --------------- Code_cpp block 1 start --------------- */
	/* --------------- Code_cpp block 1 end --------------- */

	resourcesInit();

	/* --------------- Code_cpp block 2 start --------------- */
	/* --------------- Code_cpp block 2 end --------------- */
}

Device::~Device() {
	/* --------------- Code_cpp block 3 start --------------- */
	/* --------------- Code_cpp block 3 end --------------- */
}

Resource * Device::getResource(ID_T id) {
	// Check if resource ID is valid
	if (_resources.find(id) == _resources.end()) return NULL;
	return &_resources[id];
}

std::vector<Resource *> Device::getResourcesList() {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		list.push_back(&pair.second);
	}
	return list;
}

std::vector<Resource *> Device::getResourcesList(const ResOp& filter) {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		if (filter.isCompatible(pair.second.getOperation())) list.push_back(&pair.second);
	}
	return list;
}

std::vector<Resource *> Device::getInstantiatedResourcesList() {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		if (!pair.second.isEmpty()) list.push_back(&pair.second);
	}
	return list;
}

std::vector<Resource *> Device::getInstantiatedResourcesList(const ResOp& filter) {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		if (!pair.second.isEmpty() && filter.isCompatible(pair.second.getOperation())) list.push_back(&pair.second);
	}
	return list;
}

void Device::setDefaultState() {
	/* --------------- Code_cpp block 4 start --------------- */
	/* --------------- Code_cpp block 4 end --------------- */

	for (auto &pair : _resources) pair.second.clear();
	resourcesInit();

	/* --------------- Code_cpp block 5 start --------------- */
	/* --------------- Code_cpp block 5 end --------------- */
}

void Device::serverOperationNotifier(ResOp::TYPE type, const ResLink &resId) {
	/* --------------- Code_cpp block 6 start --------------- */
	/* --------------- Code_cpp block 6 end --------------- */

	observerNotify(*this, resId, type);

	/* --------------- Code_cpp block 7 start --------------- */
	switch (type) {
	case ResOp::READ:
		WPP_LOGD_ARG(TAG, "Server READ -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::WRITE:
		WPP_LOGD_ARG(TAG, "Server WRITE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::EXECUTE:
		WPP_LOGD_ARG(TAG, "Server EXECUTE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::DISCOVER:
		WPP_LOGD_ARG(TAG, "Server DISCOVER -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::DELETE:
		WPP_LOGD_ARG(TAG, "Server DELETE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	default: break;
	}
	/* --------------- Code_cpp block 7 end --------------- */
}

void Device::userOperationNotifier(ResOp::TYPE type, const ResLink &resId) {
	/* --------------- Code_cpp block 8 start --------------- */
	switch (type) {
	case ResOp::READ:
		WPP_LOGD_ARG(TAG, "User READ -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::WRITE:
		WPP_LOGD_ARG(TAG, "User WRITE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::DELETE:
		WPP_LOGD_ARG(TAG, "User DELETE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	default: break;
	}
	/* --------------- Code_cpp block 8 end --------------- */
}

	/* --------------- Class private methods --------------- */
void Device::resourcesInit() {
	/* --------------- Code_cpp block 9 start --------------- */
	#if RES_3_0_MANUFACTURER                                                                                                                                                                                            
	_resources[MANUFACTURER_0].set(STRING_T(""));
	#endif          

	#if RES_3_1_MODEL_NUMBER    
	_resources[MODEL_NUMBER_1].set(STRING_T(""));                                                                                                                                                                                        
	#endif                                                                                                                                                                                                              
	
	#if RES_3_2_SERIAL_NUMBER                                                                                                                                                                                           
	_resources[SERIAL_NUMBER_2].set(STRING_T("")); 
	#endif                                                                                                                                                                                                              
	
	#if RES_3_3_FIRMWARE_VERSION                                                                                                                                                                                        
	_resources[FIRMWARE_VERSION_3].set(STRING_T("")); 
	#endif                                                                                                                                                                                                                                     

	#if RES_3_6_AVAILABLE_POWER_SOURCES
	_resources[AVAILABLE_POWER_SOURCES_6].set(INT_T(PWR_SRC_MAX));
	_resources[AVAILABLE_POWER_SOURCES_6].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return DC <= value && value < PWR_SRC_MAX; });
	#endif

	#if RES_3_7_POWER_SOURCE_VOLTAGE
	_resources[POWER_SOURCE_VOLTAGE_7].set(INT_T(0));                                                                                                                                                                                 
	#endif                                                                                                                                                                                                              
	
	#if RES_3_8_POWER_SOURCE_CURRENT
	_resources[POWER_SOURCE_CURRENT_8].set(INT_T(0));                                                                                                                                                                                  
	#endif 
	
	#if RES_3_9_BATTERY_LEVEL
	_resources[BATTERY_LEVEL_9].set(INT_T(BUTT_LVL_MIN));
	_resources[BATTERY_LEVEL_9].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return BUTT_LVL_MIN <= value && value <= BUTT_LVL_MAX; });
	#endif

	#if RES_3_10_MEMORY_FREE
	_resources[MEMORY_FREE_10].set(INT_T(0));                                                                                                                                                                                         
	#endif

	_resources[ERROR_CODE_11].set((INT_T)NO_ERROR);
	_resources[ERROR_CODE_11].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return NO_ERROR <= value && value < ERR_CODE_MAX; });
	
	#if RES_3_12_RESET_ERROR_CODE
	_resources[RESET_ERROR_CODE_12].set((EXECUTE_T)[this](ID_T id, const OPAQUE_T& buff) { 
		this->_resources[ERROR_CODE_11].clear();
		_resources[ERROR_CODE_11].set((INT_T)NO_ERROR);
	});
	#endif

	#if RES_3_13_CURRENT_TIME
	_resources[CURRENT_TIME_13].set(TIME_T(0));                                                                                                                                                                                       
	#endif                                                                                                                                                                                                              
	
	#if RES_3_14_UTC_OFFSET
	_resources[UTC_OFFSET_14].set(STRING_T(""));                                                                                                                                                                                             
	#endif                                                                                                                                                                                                              
	
	#if RES_3_15_TIMEZONE 
	_resources[TIMEZONE_15].set(STRING_T(""));                                                                                                                                                                                     
	#endif

	_resources[SUPPORTED_BINDING_AND_MODES_16].set(STRING_T(""));
	_resources[SUPPORTED_BINDING_AND_MODES_16].setDataVerifier((VERIFY_STRING_T)([](const STRING_T& value) { return wppBindingValidate(value); }));

	#if RES_3_17_DEVICE_TYPE 
	_resources[DEVICE_TYPE_17].set(STRING_T(""));                                                                                                                                                                                           
	#endif

	#if RES_3_18_HARDWARE_VERSION
	_resources[HARDWARE_VERSION_18].set(STRING_T(""));                                                                                                                                                                              
	#endif                                                                                                                                                                                                              
	
	#if RES_3_19_SOFTWARE_VERSION
	_resources[SOFTWARE_VERSION_19].set(STRING_T(""));                                                                                                                                                                                    
	#endif                 

	#if RES_3_20_BATTERY_STATUS
	_resources[BATTERY_STATUS_20].set(INT_T(BUTT_STATUS_MAX));
	_resources[BATTERY_STATUS_20].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return NORMAL <= value && value < BUTT_STATUS_MAX; });
	#endif

	#if RES_3_21_MEMORY_TOTAL                                                                                                                                                                                           
	_resources[MEMORY_TOTAL_21].set((INT_T)NO_ERROR);
	#endif                                                                                                                                                                                                              
	
	#if RES_3_22_EXTDEVINFO                                                                                                                                                                                         
	_resources[EXTDEVINFO_22].set(OBJ_LINK_T());
	#endif     
	/* --------------- Code_cpp block 9 end --------------- */
}

/* --------------- Code_cpp block 10 start --------------- */
/* --------------- Code_cpp block 10 end --------------- */

} /* namespace wpp */
