/*
 * Device
 * Generated on: 2023-10-12 16:31:46.234714
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#ifndef WPP_M_3_DEVICE_V12_H
#define WPP_M_3_DEVICE_V12_H

#include "DeviceConfig.h"
#include "DeviceInfo.h"
#include "Instance.h"
#include "InstSubject.h"

/* --------------- Сode_h block 0 start --------------- */
#include "WppBindings.h"
/* --------------- Сode_h block 0 end --------------- */

namespace wpp {

class Device : public Instance, public InstSubject<Device> {
public:
	enum ID: ID_T {
		MANUFACTURER_0 = 0,
		MODEL_NUMBER_1 = 1,
		SERIAL_NUMBER_2 = 2,
		FIRMWARE_VERSION_3 = 3,
		REBOOT_4 = 4,
		FACTORY_RESET_5 = 5,
		AVAILABLE_POWER_SOURCES_6 = 6,
		POWER_SOURCE_VOLTAGE_7 = 7,
		POWER_SOURCE_CURRENT_8 = 8,
		BATTERY_LEVEL_9 = 9,
		MEMORY_FREE_10 = 10,
		ERROR_CODE_11 = 11,
		RESET_ERROR_CODE_12 = 12,
		CURRENT_TIME_13 = 13,
		UTC_OFFSET_14 = 14,
		TIMEZONE_15 = 15,
		SUPPORTED_BINDING_AND_MODES_16 = 16,
		DEVICE_TYPE_17 = 17,
		HARDWARE_VERSION_18 = 18,
		SOFTWARE_VERSION_19 = 19,
		BATTERY_STATUS_20 = 20,
		MEMORY_TOTAL_21 = 21,
		EXTDEVINFO_22 = 22,
	};

	/* --------------- Code_h block 1 start --------------- */
	#if RES_AVAILABLE_POWER_SOURCES_3_6
	enum PwrSrcs: uint8_t {
		DC = 0,
		INTERN_BUTT = 1,
		EXTERN_BUTT = 2,
		FUEL_CELL = 3,
		PWR_OVER_ETHERNET = 4,
		USB = 5,
		AC = 6,
		SOLAR = 7,
		PWR_SRC_MAX
	};
	#endif

	enum ErrCode: uint8_t {
		NO_ERROR = 0,
		LOW_BUTT = 1,
		EXT_PWR_SUPP_OFF = 2,
		GPS_FAIL = 3,
		LOW_SIG_STRENGTH = 4,
		OUT_OF_MEM = 5,
		SMS_FAIL = 6,
		IP_CONN_FAIL = 7,
		PERIPH_FAIL = 8,
		ERR_CODE_MAX
	};

	#if RES_BATTERY_STATUS_3_20
	enum ButtStatus {
		NORMAL = 0,
		CHARGING = 1,
		CHARGED = 2,
		DAMAGED = 3,
		LOW_BATTERY = 4,
		NOT_INSTALLED = 5,
		UNKNOWN = 6,
		BUTT_STATUS_MAX
	};
	#endif
	/* --------------- Code_h block 1 end --------------- */

public:
	Device(lwm2m_context_t &context, const OBJ_LINK_T &id);
	~Device();

	/* --------------- Code_h block 2 start --------------- */
	/* --------------- Code_h block 2 end --------------- */

protected:
	/* --------------- Instance implementation part --------------- */
	/* 
	 * Returns Resource object if it is exist
	 */
	Resource * getResource(ID_T id) override;
	/*
	 * Returns list with available resources
	 */
	std::vector<Resource *> getResourcesList() override;
	std::vector<Resource *> getResourcesList(const ResOp& filter) override;
	/*
	 * Returns list with available instantiated resources
	 */
	std::vector<Resource *> getInstantiatedResourcesList() override;
	std::vector<Resource *> getInstantiatedResourcesList(const ResOp& filter) override;
	/*
	 * Reset all resources values and internal state to default.
	 */
	void setDefaultState() override;
	/*
	 * Handles information about resource operation that made server
	 */
	void serverOperationNotifier(ResOp::TYPE type, const ResLink &resId) override;
	/*
	 * Handles information about resource operation that made user
	 */
	void userOperationNotifier(ResOp::TYPE type, const ResLink &resId) override;

private:
	/* --------------- Class private methods --------------- */
	/*
	 * Initialize resources with default values
	 * Resource always must have at least one instance.
	 * Note: From server side, empty resource == undefined resource.
	 */	
	void resourcesInit();
	
	/* --------------- Code_h block 3 start --------------- */
	/* --------------- Code_h block 3 end --------------- */

private:
	std::unordered_map<ID_T, Resource> _resources = {
		// KEY   VALUE
		#if RES_3_0_MANUFACTURER                                                                                                                                                                                            
		{MANUFACTURER_0,                           {MANUFACTURER_0,                        ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_1_MODEL_NUMBER                                                                                                                                                                                            
		{MODEL_NUMBER_1,                           {MODEL_NUMBER_1,                        ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_2_SERIAL_NUMBER                                                                                                                                                                                           
		{SERIAL_NUMBER_2,                          {SERIAL_NUMBER_2,                       ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_3_FIRMWARE_VERSION                                                                                                                                                                                        
		{FIRMWARE_VERSION_3,                       {FIRMWARE_VERSION_3,                    ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		{REBOOT_4,                                 {REBOOT_4,                              ResOp(ResOp::EXECUTE),                  IS_SINGLE::SINGLE,          IS_MANDATORY::MANDATORY,        TYPE_ID::EXECUTE }},         
		#if RES_3_5_FACTORY_RESET                                                                                                                                                                                           
		{FACTORY_RESET_5,                          {FACTORY_RESET_5,                       ResOp(ResOp::EXECUTE),                  IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::EXECUTE }},         
		#endif                                                                                                                                                                                                              
		#if RES_3_6_AVAILABLE_POWER_SOURCES                                                                                                                                                                                 
		{AVAILABLE_POWER_SOURCES_6,                {AVAILABLE_POWER_SOURCES_6,             ResOp(ResOp::READ),                     IS_SINGLE::MULTIPLE,        IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		#if RES_3_7_POWER_SOURCE_VOLTAGE                                                                                                                                                                                    
		{POWER_SOURCE_VOLTAGE_7,                   {POWER_SOURCE_VOLTAGE_7,                ResOp(ResOp::READ),                     IS_SINGLE::MULTIPLE,        IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		#if RES_3_8_POWER_SOURCE_CURRENT                                                                                                                                                                                    
		{POWER_SOURCE_CURRENT_8,                   {POWER_SOURCE_CURRENT_8,                ResOp(ResOp::READ),                     IS_SINGLE::MULTIPLE,        IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		#if RES_3_9_BATTERY_LEVEL                                                                                                                                                                                           
		{BATTERY_LEVEL_9,                          {BATTERY_LEVEL_9,                       ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		#if RES_3_10_MEMORY_FREE                                                                                                                                                                                            
		{MEMORY_FREE_10,                           {MEMORY_FREE_10,                        ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		{ERROR_CODE_11,                            {ERROR_CODE_11,                         ResOp(ResOp::READ),                     IS_SINGLE::MULTIPLE,        IS_MANDATORY::MANDATORY,        TYPE_ID::INT }},             
		#if RES_3_12_RESET_ERROR_CODE                                                                                                                                                                                       
		{RESET_ERROR_CODE_12,                      {RESET_ERROR_CODE_12,                   ResOp(ResOp::EXECUTE),                  IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::EXECUTE }},         
		#endif                                                                                                                                                                                                              
		#if RES_3_13_CURRENT_TIME                                                                                                                                                                                           
		{CURRENT_TIME_13,                          {CURRENT_TIME_13,                       ResOp(ResOp::READ|ResOp::WRITE),        IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::TIME }},            
		#endif                                                                                                                                                                                                              
		#if RES_3_14_UTC_OFFSET                                                                                                                                                                                             
		{UTC_OFFSET_14,                            {UTC_OFFSET_14,                         ResOp(ResOp::READ|ResOp::WRITE),        IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_15_TIMEZONE                                                                                                                                                                                               
		{TIMEZONE_15,                              {TIMEZONE_15,                           ResOp(ResOp::READ|ResOp::WRITE),        IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		{SUPPORTED_BINDING_AND_MODES_16,           {SUPPORTED_BINDING_AND_MODES_16,        ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::MANDATORY,        TYPE_ID::STRING }},          
		#if RES_3_17_DEVICE_TYPE                                                                                                                                                                                            
		{DEVICE_TYPE_17,                           {DEVICE_TYPE_17,                        ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_18_HARDWARE_VERSION                                                                                                                                                                                       
		{HARDWARE_VERSION_18,                      {HARDWARE_VERSION_18,                   ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_19_SOFTWARE_VERSION                                                                                                                                                                                       
		{SOFTWARE_VERSION_19,                      {SOFTWARE_VERSION_19,                   ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::STRING }},          
		#endif                                                                                                                                                                                                              
		#if RES_3_20_BATTERY_STATUS                                                                                                                                                                                         
		{BATTERY_STATUS_20,                        {BATTERY_STATUS_20,                     ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		#if RES_3_21_MEMORY_TOTAL                                                                                                                                                                                           
		{MEMORY_TOTAL_21,                          {MEMORY_TOTAL_21,                       ResOp(ResOp::READ),                     IS_SINGLE::SINGLE,          IS_MANDATORY::OPTIONAL,         TYPE_ID::INT }},             
		#endif                                                                                                                                                                                                              
		#if RES_3_22_EXTDEVINFO                                                                                                                                                                                             
		{EXTDEVINFO_22,                            {EXTDEVINFO_22,                         ResOp(ResOp::READ),                     IS_SINGLE::MULTIPLE,        IS_MANDATORY::OPTIONAL,         TYPE_ID::OBJ_LINK }},        
		#endif                                                                                                                                                                                                              
	};

	/* --------------- Code_h block 4 start --------------- */
	/* --------------- Code_h block 4 end --------------- */
};

} /* namespace wpp */

#endif /* WPP_M_3_DEVICE_V12_H */
