/*
 * Generated on: 2023-10-27 20:54:31
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#ifndef WPP_DEVICE_CONFIG_H
#define WPP_DEVICE_CONFIG_H

#if OBJ_M_3_DEVICE_V12

/* --------------- Config block 0 start --------------- */
#define RES_3_0 1
#define RES_3_1 1
#define RES_3_2 1
/* --------------- Config block 0 end --------------- */

#endif // WPP_DEVICE_CONFIG_H
#endif // OBJ_M_3_DEVICE_V12
