/*
 * File type: FILE_TYPE_OBJ_CFG
 * Generated on: 2023-10-13 18:40:08
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#ifndef WPP_LWM2M_SERVER_CONFIG_H
#define WPP_LWM2M_SERVER_CONFIG_H

#if OBJ_M_1_LWM2M_SERVER_V11

/* --------------- Config block 0 start --------------- */
/* --------------- Config block 0 end --------------- */

#endif // WPP_LWM2M_SERVER_CONFIG_H
#endif // OBJ_M_1_LWM2M_SERVER_V11
