#ifndef WPP_LWM2M_SECURITY_1_2_CONFIG_H
#define WPP_LWM2M_SECURITY_1_2_CONFIG_H

#if OBJ_LWM2M_SECURITY_1_2_M

/* ---------- Server optional resources start ---------- */

#define RES_SMS_SECURITY_MODE_0_6 0
#define RES_SMS_BINDING_KEY_PARAMETERS_0_7 0
#define RES_SMS_BINDING_SECRET_KEY_S__0_8 0
#define RES_LWM2M_SERVER_SMS_NUMBER_0_9 0
#define RES_SHORT_SERVER_ID_0_10 0
#define RES_CLIENT_HOLD_OFF_TIME_0_11 0
#define RES_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_0_12 0
#define RES_MATCHING_TYPE_0_13 0
#define RES_SNI_0_14 0
#define RES_CERTIFICATE_USAGE_0_15 0
#define RES_DTLS_TLS_CIPHERSUITE_0_16 0
#define RES_OSCORE_SECURITY_MODE_0_17 0
#define RES_GROUPS_TO_USE_BY_CLIENT_0_18 0
#define RES_SIGNATURE_ALGORITHMS_SUPPORTED_BY_SERVER_0_19 0
#define RES_SIGNATURE_ALGORITHMS_TO_USE_BY_CLIENT_0_20 0
#define RES_SIGNATURE_ALGORITHM_CERTS_SUPPORTED_BY_SERVER_0_21 0
#define RES_TLS_1_3_FEATURES_TO_USE_BY_CLIENT_0_22 0
#define RES_TLS_EXTENSIONS_SUPPORTED_BY_SERVER_0_23 0
#define RES_TLS_EXTENSIONS_TO_USE_BY_CLIENT_0_24 0
#define RES_SECONDARY_LWM2M_SERVER_URI_0_25 0
#define RES_MQTT_SERVER_0_26 0
#define RES_LWM2M_COSE_SECURITY_0_27 0
#define RES_RDS_DESTINATION_PORT_0_28 0
#define RES_RDS_SOURCE_PORT_0_29 0
#define RES_RDS_APPLICATION_ID_0_30 0

/* ---------- Server optional resources end ---------- */

/* --------------- Config block 0 start --------------- */
/* --------------- Config block 0 end --------------- */

#endif // WPP_LWM2M_SECURITY_1_2_CONFIG_H
#endif // OBJ_LWM2M_SECURITY_1_2_M
