/*
 * WppDevice
 * Generated on: 2023-10-11 15:40:32.908209
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#include "device_1_2/WppDevice.h"

#include <unordered_map>
#include <iostream>

#include "Resource.h"
#include "ResOp.h"
#include "types.h"
#include "WppLogs.h"

/* --------------- Code_cpp block 0 start --------------- */
#if RES_BATTERY_LEVEL_3_9
#define BUTT_LVL_MIN	0
#define BUTT_LVL_MAX	100
#endif
/* --------------- Code_cpp block 0 end --------------- */

#define TAG "WppDevice"

namespace wpp {

WppDevice::WppDevice(lwm2m_context_t &context, const OBJ_LINK_T &id): Instance(context, id) {

	/* --------------- Code_cpp block 1 start --------------- */
	/* --------------- Code_cpp block 1 end --------------- */

	resourcesInit();

	/* --------------- Code_cpp block 2 start --------------- */
	/* --------------- Code_cpp block 2 end --------------- */
}

WppDevice::~WppDevice() {
	/* --------------- Code_cpp block 3 start --------------- */
	/* --------------- Code_cpp block 3 end --------------- */
}

Resource * WppDevice::getResource(ID_T id) {
	// Check if resource ID is valid
	if (_resources.find(id) == _resources.end()) return NULL;
	return &_resources[id];
}

std::vector<Resource *> WppDevice::getResourcesList() {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		list.push_back(&pair.second);
	}
	return list;
}

std::vector<Resource *> WppDevice::getResourcesList(const ResOp& filter) {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		if (filter.isCompatible(pair.second.getOperation())) list.push_back(&pair.second);
	}
	return list;
}

std::vector<Resource *> WppDevice::getInstantiatedResourcesList() {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		if (!pair.second.isEmpty()) list.push_back(&pair.second);
	}
	return list;
}

std::vector<Resource *> WppDevice::getInstantiatedResourcesList(const ResOp& filter) {
	std::vector<Resource *> list;
	for (auto &pair : _resources) {
		if (!pair.second.isEmpty() && filter.isCompatible(pair.second.getOperation())) list.push_back(&pair.second);
	}
	return list;
}

void WppDevice::setDefaultState() {
	/* --------------- Code_cpp block 4 start --------------- */
	/* --------------- Code_cpp block 4 end --------------- */

	for (auto &pair : _resources) pair.second.clear();
	resourcesInit();

	/* --------------- Code_cpp block 5 start --------------- */
	/* --------------- Code_cpp block 5 end --------------- */
}

void WppDevice::serverOperationNotifier(ResOp::TYPE type, const ResLink &resId) {
	/* --------------- Code_cpp block 6 start --------------- */
	/* --------------- Code_cpp block 6 end --------------- */

	observerNotify(*this, resId, type);

	/* --------------- Code_cpp block 7 start --------------- */
	switch (type) {
	case ResOp::READ:
		WPP_LOGD_ARG(TAG, "Server READ -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::WRITE:
		WPP_LOGD_ARG(TAG, "Server WRITE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::EXECUTE:
		WPP_LOGD_ARG(TAG, "Server EXECUTE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::DISCOVER:
		WPP_LOGD_ARG(TAG, "Server DISCOVER -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::DELETE:
		WPP_LOGD_ARG(TAG, "Server DELETE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	default: break;
	}
	/* --------------- Code_cpp block 7 end --------------- */
}

void WppDevice::userOperationNotifier(ResOp::TYPE type, const ResLink &resId) {
	/* --------------- Code_cpp block 8 start --------------- */
	switch (type) {
	case ResOp::READ:
		WPP_LOGD_ARG(TAG, "User READ -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::WRITE:
		WPP_LOGD_ARG(TAG, "User WRITE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	case ResOp::DELETE:
		WPP_LOGD_ARG(TAG, "User DELETE -> resId: %d, resInstId: %d", resId.resId, resId.resInstId);
		break;
	default: break;
	}
	/* --------------- Code_cpp block 8 end --------------- */
}

	/* --------------- Class private methods --------------- */
void WppDevice::resourcesInit() {
	/* --------------- Code_cpp block 9 start --------------- */
	#if RES_MANUFACTURER_3_0                                                                                                                                                                                            
	_resources[MANUFACTURER_0].set(STRING_T(""));
	#endif          

	#if RES_MODEL_NUMBER_3_1    
	_resources[MODEL_NUMBER_1].set(STRING_T(""));                                                                                                                                                                                        
	#endif                                                                                                                                                                                                              
	
	#if RES_SERIAL_NUMBER_3_2                                                                                                                                                                                           
	_resources[SERIAL_NUMBER_2].set(STRING_T("")); 
	#endif                                                                                                                                                                                                              
	
	#if RES_FIRMWARE_VERSION_3_3                                                                                                                                                                                        
	_resources[FIRMWARE_VERSION_3].set(STRING_T("")); 
	#endif                                                                                                                                                                                                                                     

	#if RES_AVAILABLE_POWER_SOURCES_3_6
	_resources[AVAILABLE_POWER_SOURCES_6].set(INT_T(PWR_SRC_MAX));
	_resources[AVAILABLE_POWER_SOURCES_6].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return DC <= value && value < PWR_SRC_MAX; });
	#endif

	#if RES_POWER_SOURCE_VOLTAGE_3_7
	_resources[POWER_SOURCE_VOLTAGE_7].set(INT_T(0));                                                                                                                                                                                 
	#endif                                                                                                                                                                                                              
	
	#if RES_POWER_SOURCE_CURRENT_3_8
	_resources[POWER_SOURCE_CURRENT_8].set(INT_T(0));                                                                                                                                                                                  
	#endif 
	
	#if RES_BATTERY_LEVEL_3_9
	_resources[BATTERY_LEVEL_9].set(INT_T(BUTT_LVL_MIN));
	_resources[BATTERY_LEVEL_9].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return BUTT_LVL_MIN <= value && value <= BUTT_LVL_MAX; });
	#endif

	#if RES_MEMORY_FREE_3_10
	_resources[MEMORY_FREE_10].set(INT_T(0));                                                                                                                                                                                         
	#endif

	_resources[ERROR_CODE_11].set((INT_T)NO_ERROR);
	_resources[ERROR_CODE_11].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return NO_ERROR <= value && value < ERR_CODE_MAX; });
	
	#if RES_RESET_ERROR_CODE_3_12
	_resources[RESET_ERROR_CODE_12].set((EXECUTE_T)[this](ID_T id, const OPAQUE_T& buff) { 
		this->_resources[ERROR_CODE_11].clear();
		_resources[ERROR_CODE_11].set((INT_T)NO_ERROR);
	});
	#endif

	#if RES_CURRENT_TIME_3_13
	_resources[CURRENT_TIME_13].set(TIME_T(0));                                                                                                                                                                                       
	#endif                                                                                                                                                                                                              
	
	#if RES_UTC_OFFSET_3_14
	_resources[UTC_OFFSET_14].set(STRING_T(""));                                                                                                                                                                                             
	#endif                                                                                                                                                                                                              
	
	#if RES_TIMEZONE_3_15 
	_resources[TIMEZONE_15].set(STRING_T(""));                                                                                                                                                                                     
	#endif

	_resources[SUPPORTED_BINDING_AND_MODES_16].set(STRING_T(""));
	_resources[SUPPORTED_BINDING_AND_MODES_16].setDataVerifier((VERIFY_STRING_T)([](const STRING_T& value) { return wppBindingValidate(value); }));

	#if RES_HARDWARE_VERSION_3_18
	_resources[HARDWARE_VERSION_18].set(STRING_T(""));                                                                                                                                                                              
	#endif                                                                                                                                                                                                              
	
	#if RES_SOFTWARE_VERSION_3_19
	_resources[SOFTWARE_VERSION_19].set(STRING_T(""));                                                                                                                                                                                    
	#endif                 

	#if RES_BATTERY_STATUS_3_20
	_resources[BATTERY_STATUS_20].set(INT_T(BUTT_STATUS_MAX));
	_resources[BATTERY_STATUS_20].setDataVerifier((VERIFY_INT_T)[](const INT_T& value) { return NORMAL <= value && value < BUTT_STATUS_MAX; });
	#endif

	#if RES_MEMORY_TOTAL_3_21                                                                                                                                                                                           
	_resources[MEMORY_TOTAL_21].set((INT_T)NO_ERROR);
	#endif                                                                                                                                                                                                              
	
	#if RES_EXTDEVINFO_3_22                                                                                                                                                                                         
	_resources[EXTDEVINFO_22].set(OBJ_LINK_T());
	#endif     
	/* --------------- Code_cpp block 9 end --------------- */
}

/* --------------- Code_cpp block 10 start --------------- */
/* --------------- Code_cpp block 10 end --------------- */

} /* namespace wpp */
