/*
 * ConnectivityMonitoring
 * Generated on: 2023-10-30 17:09:17
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#ifndef WPP_O_4_CONNECTIVITY_MONITORING_V13_H
#define WPP_O_4_CONNECTIVITY_MONITORING_V13_H

#include "ConnectivityMonitoringConfig.h"
#include "ConnectivityMonitoringInfo.h"
#include "Instance.h"
#include "InstSubject.h"

/* --------------- Сode_h block 0 start --------------- */
/* --------------- Сode_h block 0 end --------------- */

namespace wpp {

class ConnectivityMonitoring : public Instance, public InstSubject<ConnectivityMonitoring> {
public:
	enum ID: ID_T {
		#if RES_4_0
		NETWORK_BEARER_0 = 0,
		#endif
		#if RES_4_1
		AVAILABLE_NETWORK_BEARER_1 = 1,
		#endif
		#if RES_4_2
		RADIO_SIGNAL_STRENGTH_2 = 2,
		#endif
		#if RES_4_3
		LINK_QUALITY_3 = 3,
		#endif
		#if RES_4_4
		IP_ADDRESSES_4 = 4,
		#endif
		#if RES_4_5
		ROUTER_IP_ADDRESSES_5 = 5,
		#endif
		#if RES_4_6
		LINK_UTILIZATION_6 = 6,
		#endif
		#if RES_4_7
		APN_7 = 7,
		#endif
		#if RES_4_8
		CELL_ID_8 = 8,
		#endif
		#if RES_4_9
		SMNC_9 = 9,
		#endif
		#if RES_4_10
		SMCC_10 = 10,
		#endif
		#if RES_4_11
		SIGNALSNR_11 = 11,
		#endif
		#if RES_4_12
		LAC_12 = 12,
		#endif
		#if RES_4_13
		COVERAGE_ENHANCEMENT_LEVEL_13 = 13,
		#endif
	};

	/* --------------- Code_h block 1 start --------------- */
	/* --------------- Code_h block 1 end --------------- */

public:
	ConnectivityMonitoring(lwm2m_context_t &context, const OBJ_LINK_T &id);
	~ConnectivityMonitoring();

	/* --------------- Code_h block 2 start --------------- */
	/* --------------- Code_h block 2 end --------------- */

protected:
	/* --------------- Instance implementation part --------------- */
	/*
	 * Reset all resources values and internal state to default.
	 */
	void setDefaultState() override;
	/*
	 * Handles information about resource operation that made server
	 */
	void serverOperationNotifier(ResOp::TYPE type, const ResLink &resId) override;
	/*
	 * Handles information about resource operation that made user
	 */
	void userOperationNotifier(ResOp::TYPE type, const ResLink &resId) override;

private:
	/* --------------- Class private methods --------------- */
	/*
	 * Creates resources without initializing.
	 */
	void resourcesCreate();
	/*
	 * Initialize resources with default values
	 * Resource always must have at least one instance.
	 * Note: From server side, empty resource == undefined resource.
	 */	
	void resourcesInit();
	
	/* --------------- Code_h block 3 start --------------- */
	/* --------------- Code_h block 3 end --------------- */

private:
	/* --------------- Code_h block 4 start --------------- */
	/* --------------- Code_h block 4 end --------------- */
};

} /* namespace wpp */

#endif /* WPP_O_4_CONNECTIVITY_MONITORING_V13_H */
