/*
 * Generated on: 2023-10-30 17:09:17
 * Author: valentin
 * Generated by: Vadimzakreva
 */

#ifndef WPP_CONNECTIVITY_MONITORING_CONFIG_H
#define WPP_CONNECTIVITY_MONITORING_CONFIG_H

#if OBJ_O_4_CONNECTIVITY_MONITORING_V13

/* --------------- Config block 0 start --------------- */
#define RES_4_3 0
#define RES_4_5 0
#define RES_4_6 0
#define RES_4_7 0
#define RES_4_8 0
#define RES_4_9 0
#define RES_4_10 0
#define RES_4_11 0
#define RES_4_12 0
#define RES_4_13 0

/* --------------- Config block 0 end --------------- */

#endif // WPP_CONNECTIVITY_MONITORING_CONFIG_H
#endif // OBJ_O_4_CONNECTIVITY_MONITORING_V13
