# generate_wpp_definitions.cmake
#
# This script generates a CMake file containing a series of 'set' commands.
# These commands are used to define configuration options based on the
# WPP_DEFINITIONS variable. Each definition in WPP_DEFINITIONS is written
# as a separate 'set' command, appended to the WPP_DEFINITIONS list.
#
# Arguments:
# - ARGV0: WPP_DEFINITIONS (string of definitions separated by spaces)
# - ARGV1: Output filename for the generated CMake file
#
# Output:
# A CMake file with the specified filename, containing formatted CMake 'set'
# commands for each definition in WPP_DEFINITIONS.

# Set input arguments
set(WPP_DEFINITIONS ${ARGV0})
set(OUTPUT_FILENAME ${ARGV1})

# Validate output filename
if(NOT OUTPUT_FILENAME)
    message(FATAL_ERROR "No output filename specified for generate_wpp_definitions.cmake")
endif()

# Create or clear the output file with an initial comment
file(WRITE "wpp_definitions.cmake" 
"# Generated CMake Definitions File
#
# This file is generated by the build system.
# It contains a series of 'set' commands, each defining a configuration option
# derived from the WPP_DEFINITIONS variable used during the build.
\n")

# Split the definitions and write each as a separate set command
string(REPLACE " " ";" DEFINITIONS_LIST "${WPP_DEFINITIONS}")
foreach(DEF IN LISTS DEFINITIONS_LIST)
    string(APPEND OUTPUT "set(WPP_DEFINITIONS \${WPP_DEFINITIONS} ${DEF})\n")
endforeach()

# Append a commad to share the definitions with the target
string(APPEND OUTPUT "\n# Share defines with target\n")
string(APPEND OUTPUT "set(WPP_DEFINITIONS \${WPP_DEFINITIONS} PARENT_SCOPE)\n")

# Write the formatted output to the file
file(APPEND "${OUTPUT_FILENAME}" "${OUTPUT}")