#ifndef WPP_LWM2M_SERVER_1_2_CONFIG_H
#define WPP_LWM2M_SERVER_1_2_CONFIG_H

#if OBJ_LWM2M_SERVER_1_2_M

/* ---------- Server optional resources start ---------- */

#define RES_DEFAULT_MINIMUM_PERIOD_1_2 0
#define RES_DEFAULT_MAXIMUM_PERIOD_1_3 0
#define RES_DISABLE_1_4 0
#define RES_DISABLE_TIMEOUT_1_5 0
#define RES_BOOTSTRAP_REQUEST_TRIGGER_1_9 0
#define RES_APN_LINK_1_10 0
#define RES_TLS_DTLS_ALERT_CODE_1_11 0
#define RES_LAST_BOOTSTRAPPED_1_12 0
#define RES_REGISTRATION_PRIORITY_ORDER_1_13 0
#define RES_INITIAL_REGISTRATION_DELAY_TIMER_1_14 0
#define RES_REGISTRATION_FAILURE_BLOCK_1_15 0
#define RES_BOOTSTRAP_ON_REGISTRATION_FAILURE_1_16 0
#define RES_COMMUNICATION_RETRY_COUNT_1_17 0
#define RES_COMMUNICATION_RETRY_TIMER_1_18 0
#define RES_COMMUNICATION_SEQUENCE_DELAY_TIMER_1_19 0
#define RES_COMMUNICATION_SEQUENCE_RETRY_COUNT_1_20 0
#define RES_TRIGGER_1_21 0
#define RES_PREFERRED_TRANSPORT_1_22 0
#define RES_MUTE_SEND_1_23 0
#define RES_ALTERNATE_APN_LINKS_1_24 0
#define RES_SUPPORTED_SERVER_VERSIONS_1_25 0
#define RES_DEFAULT_NOTIFICATION_MODE_1_26 0
#define RES_PROFILE_ID_HASH_ALGORITHM_1_27 0

/* ---------- Server optional resources end ---------- */

/* --------------- Config block 0 start --------------- */
/* --------------- Config block 0 end --------------- */

#endif // WPP_LWM2M_SERVER_1_2_CONFIG_H
#endif // OBJ_LWM2M_SERVER_1_2_M
